"""create

Revision ID: 90c8fb248bc0
Revises: 
Create Date: 2026-02-06 11:18:35.882153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c8fb248bc0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Test',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Test_Name'), 'Test', ['Name'], unique=True)
    op.create_table('Matches',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', sa.String(length=36), nullable=False),
    sa.Column('Player1', sa.Integer(), nullable=False),
    sa.Column('Player2', sa.Integer(), nullable=False),
    sa.Column('Winner', sa.Integer(), nullable=True),
    sa.Column('Score', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['Player1'], ['Players.ID'], ),
    sa.ForeignKeyConstraint(['Player2'], ['Players.ID'], ),
    sa.ForeignKeyConstraint(['Winner'], ['Players.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('UUID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_index(op.f('ix_Test_Name'), table_name='Test')
    op.drop_table('Test')
    # ### end Alembic commands ###
