"""add table Player2

Revision ID: 921fc55525e8
Revises: d3ef9c70ea18
Create Date: 2026-02-06 11:23:23.955227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921fc55525e8'
down_revision: Union[str, Sequence[str], None] = 'd3ef9c70ea18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Players2',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Players2_Name'), 'Players2', ['Name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Players2_Name'), table_name='Players2')
    op.drop_table('Players2')
    # ### end Alembic commands ###
