"""initial_schema_with_json_score

Revision ID: c96aadc41f48
Revises: 
Create Date: 2026-02-25 12:02:49.808900

"""
# Standard library imports
from typing import Sequence, Union

# Third party imports
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'c96aadc41f48'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Players',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_Players_Name'), 'Players', ['Name'], unique=True)
    op.create_table('Matches',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('UUID', sa.String(length=36), nullable=False),
    sa.Column('Player1', sa.Integer(), nullable=False),
    sa.Column('Player2', sa.Integer(), nullable=False),
    sa.Column('Winner', sa.Integer(), nullable=True),
    sa.Column('Score', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['Player1'], ['Players.ID'], ),
    sa.ForeignKeyConstraint(['Player2'], ['Players.ID'], ),
    sa.ForeignKeyConstraint(['Winner'], ['Players.ID'], ),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('UUID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Matches')
    op.drop_index(op.f('ix_Players_Name'), table_name='Players')
    op.drop_table('Players')
    # ### end Alembic commands ###
